{% set name = "pyan3" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyan3-{{ version }}.tar.gz
  sha256: f4f81d2c629cbc62b7e5ad8d828a0d9bf79229b3b8598c3d39725a8540565c79

build:
  number: 0
  noarch: python
  entry_points:
    - pyan3 = pyan.main:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - jinja2
    - python >={{ python_min }}

test:
  imports:
    - pyan
  commands:
    - pip check
    - pyan3 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Technologicat/pyan
  summary: Offline call graph generator for Python 3
  license: GPL-2.0-only
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - thewchan
