schema_version: 1

context:
  name: pyan3
  version: "2.4.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyan3-${{ version }}.tar.gz
  sha256: 32dfbdf4c6e2de6fdce0c96d7be8d139a6fe604e236ca5a2f6764fdaa9c5ef5b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pyan3 = pyan.main:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - hatchling
  run:
    - jinja2
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pyan
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pyan3 --help

about:
  summary: Offline call graph generator for Python 3
  license: GPL-2.0-only
  license_file: LICENSE.md
  homepage: https://github.com/Technologicat/pyan

extra:
  recipe-maintainers:
    - thewchan
